version: "3.9"

services:
  frontend:
    image: frontend
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      args:
        - ENV=$ENV
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
