import './globals.css';
import React from 'react';
import CombineProvider from '@/app/CombineProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({children}) => {
  return (
    <html lang="fa">
    <body className={'!font-samim'}>
    <div className="--hiradApp h-full">
      <CombineProvider>
        {children}
      </CombineProvider>
    </div>
    </body>
    </html>
  );
};

export default RootLayout;
